#include <iostream>
using namespace std;

double f(int n)
{
    float m;
    if (n==0||n==1)
        m=1;
    else if (n>1)
        m=f(n-1)*n;
    return m;
}

int main()
{
    double a,sum=2.5;
    int i;
    printf("n e\n");
	printf("- -----------\n");
    printf("0 1\n1 2\n2 2.5\n");
    for (i=3; i<10; i++) {
        a=1/f(i);
        sum=sum+a;
        printf("%d %.9f\n",i,sum);
    }
    return 0;
}
/*
 Description
 
 A simple mathematical formula for e is 
 e=Σ0<=i<=n1/i!
 
 where n is allowed to go to infinity. This can actually yield very accurate approximations of e using relatively small values of n.
 Input
 
 No input
 Output
 
 Output the approximations of e generated by the above formula for the values of n from 0 to 9. The beginning of your output should appear similar to that shown below.
 Sample Input
 
 no input
 Sample Output
 
 n e
 - -----------
 0 1
 1 2
 2 2.5
 3 2.666666667
 4 2.708333333
 ...
*/